# Generated by Django 3.1 on 2020-12-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
